import type { AiringStatus, ShowType } from "../../src/generated/prisma/enums";

/**
 * Development catalogue.
 *
 * Season and episode counts are the real ones, because the whole product is
 * built on exact progress: a seeded Breaking Bad has to be 62 episodes across
 * 7/13/13/13/16, or every percentage and completion test is testing fiction.
 *
 * What is *not* real here is artwork. Rather than hot-link posters we do not
 * have the rights to, or ship a folder of placeholder JPEGs, seeded shows have
 * no poster and the UI renders a deterministic gradient from the title (see
 * ShowPoster). Point `METADATA_PROVIDER` at TMDB and real artwork flows in
 * through the provider with no code change.
 *
 * Episode titles are generated except where a marquee show has them listed —
 * inventing plausible-looking fake titles would make the seed harder to trust,
 * not easier.
 */

export interface SeedSeason {
  number: number;
  episodes: number;
  /** Real episode titles, index-aligned from episode 1. Optional. */
  titles?: string[];
  year?: number;
}

export interface SeedShow {
  externalId: string;
  type: ShowType;
  title: string;
  originalTitle?: string;
  synopsis: string;
  firstAirYear: number;
  lastAirYear?: number;
  airingStatus: AiringStatus;
  runtime: number;
  language: string;
  popularity: number;
  externalRating: number;
  genres: string[];
  credits: { name: string; kind: "STUDIO" | "NETWORK" }[];
  seasons: SeedSeason[];
}

const BREAKING_BAD_S1 = [
  "Pilot",
  "Cat's in the Bag...",
  "...And the Bag's in the River",
  "Cancer Man",
  "Gray Matter",
  "Crazy Handful of Nothin'",
  "A No-Rough-Stuff-Type Deal",
];

const ATTACK_ON_TITAN_S1 = [
  "To You, in 2000 Years: The Fall of Shiganshina, Part 1",
  "That Day: The Fall of Shiganshina, Part 2",
  "A Dim Light Amid Despair: Humanity's Comeback, Part 1",
  "The Night of the Closing Ceremony: Humanity's Comeback, Part 2",
  "First Battle: The Struggle for Trost, Part 1",
  "The World the Girl Saw: The Struggle for Trost, Part 2",
  "Small Blade: The Struggle for Trost, Part 3",
  "I Can Hear His Heartbeat: The Struggle for Trost, Part 4",
  "Whereabouts of His Left Arm: The Struggle for Trost, Part 5",
  "Response: The Struggle for Trost, Part 6",
  "Idol: The Struggle for Trost, Part 7",
  "Wound: The Struggle for Trost, Part 8",
  "Primal Desire: The Struggle for Trost, Part 9",
  "Can't Look into His Eyes: Eve of the Counterattack, Part 1",
  "Special Operations Squad: Eve of the Counterattack, Part 2",
  "What Needs to be Done Now: Eve of the Counterattack, Part 3",
  "Female Titan: The 57th Exterior Scouting Mission, Part 1",
  "Forest of Giant Trees: The 57th Exterior Scouting Mission, Part 2",
  "Bite: The 57th Exterior Scouting Mission, Part 3",
  "Erwin Smith: The 57th Exterior Scouting Mission, Part 4",
  "Crushing Blow: The 57th Exterior Scouting Mission, Part 5",
  "The Defeated: The 57th Exterior Scouting Mission, Part 6",
  "Smile: Assault on Stohess, Part 1",
  "Mercy: Assault on Stohess, Part 2",
  "Wall: Assault on Stohess, Part 3",
];

const CHERNOBYL = ["1:23:45", "Please Remain Calm", "Open Wide, O Earth", "The Happiness of All Mankind", "Vichnaya Pamyat"];

/** Anime. */
export const SEED_ANIME: SeedShow[] = [
  {
    externalId: "anime-attack-on-titan",
    type: "ANIME",
    title: "Attack on Titan",
    originalTitle: "Shingeki no Kyojin",
    synopsis:
      "Humanity lives caged behind enormous walls, hunted by man-eating giants. When the outermost wall falls, a boy who watched his mother die swears to kill every last titan — and learns, slowly and horribly, what the walls were really built to keep in.",
    firstAirYear: 2013,
    lastAirYear: 2023,
    airingStatus: "ENDED",
    runtime: 24,
    language: "ja",
    popularity: 98.4,
    externalRating: 8.9,
    genres: ["Action", "Drama", "Fantasy", "Psychological"],
    credits: [{ name: "Wit Studio", kind: "STUDIO" }, { name: "MAPPA", kind: "STUDIO" }],
    seasons: [
      { number: 1, episodes: 25, titles: ATTACK_ON_TITAN_S1, year: 2013 },
      { number: 2, episodes: 12, year: 2017 },
      { number: 3, episodes: 22, year: 2018 },
      { number: 4, episodes: 30, year: 2020 },
    ],
  },
  {
    externalId: "anime-death-note",
    type: "ANIME",
    title: "Death Note",
    synopsis:
      "A bored honour student finds a notebook that kills anyone whose name is written in it. What starts as cleaning up the world becomes a two-man chess game between a god complex and a detective who eats too much cake.",
    firstAirYear: 2006,
    lastAirYear: 2007,
    airingStatus: "ENDED",
    runtime: 23,
    language: "ja",
    popularity: 94.1,
    externalRating: 8.6,
    genres: ["Mystery", "Psychological", "Thriller", "Supernatural"],
    credits: [{ name: "Madhouse", kind: "STUDIO" }],
    seasons: [{ number: 1, episodes: 37, year: 2006 }],
  },
  {
    externalId: "anime-one-piece",
    type: "ANIME",
    title: "One Piece",
    synopsis:
      "A rubber boy with a straw hat sails to find the world's greatest treasure. Twenty-five years later he is still sailing, and so are you.",
    firstAirYear: 1999,
    airingStatus: "AIRING",
    runtime: 24,
    language: "ja",
    popularity: 99.8,
    externalRating: 8.7,
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
    credits: [{ name: "Toei Animation", kind: "STUDIO" }],
    seasons: [
      { number: 1, episodes: 61, year: 1999 },
      { number: 2, episodes: 16, year: 2001 },
      { number: 3, episodes: 13, year: 2001 },
      { number: 4, episodes: 39, year: 2001 },
      { number: 5, episodes: 14, year: 2002 },
      { number: 6, episodes: 51, year: 2002 },
      { number: 7, episodes: 35, year: 2003 },
      { number: 8, episodes: 39, year: 2004 },
      { number: 9, episodes: 69, year: 2005 },
      { number: 10, episodes: 32, year: 2007 },
      { number: 11, episodes: 55, year: 2008 },
      { number: 12, episodes: 100, year: 2009 },
      { number: 13, episodes: 35, year: 2011 },
      { number: 14, episodes: 46, year: 2012 },
      { number: 15, episodes: 62, year: 2013 },
      { number: 16, episodes: 39, year: 2014 },
      { number: 17, episodes: 118, year: 2015 },
      { number: 18, episodes: 35, year: 2017 },
      { number: 19, episodes: 43, year: 2018 },
      { number: 20, episodes: 195, year: 2019 },
      { number: 21, episodes: 25, year: 2023 },
    ],
  },
  {
    externalId: "anime-naruto",
    type: "ANIME",
    title: "Naruto",
    synopsis:
      "An orphan with a demon fox sealed inside him wants to be recognised by a village that will not look at him. Contains an unreasonable amount of running.",
    firstAirYear: 2002,
    lastAirYear: 2007,
    airingStatus: "ENDED",
    runtime: 23,
    language: "ja",
    popularity: 91.2,
    externalRating: 8.3,
    genres: ["Action", "Adventure", "Fantasy"],
    credits: [{ name: "Studio Pierrot", kind: "STUDIO" }],
    seasons: [
      { number: 1, episodes: 57, year: 2002 },
      { number: 2, episodes: 43, year: 2003 },
      { number: 3, episodes: 43, year: 2004 },
      { number: 4, episodes: 43, year: 2005 },
      { number: 5, episodes: 34, year: 2006 },
    ],
  },
  {
    externalId: "anime-jujutsu-kaisen",
    type: "ANIME",
    title: "Jujutsu Kaisen",
    synopsis:
      "A high schooler swallows a cursed finger to save his friends and becomes the vessel for the king of curses. Everyone involved handles this badly.",
    firstAirYear: 2020,
    airingStatus: "AIRING",
    runtime: 24,
    language: "ja",
    popularity: 96.7,
    externalRating: 8.6,
    genres: ["Action", "Supernatural", "Fantasy"],
    credits: [{ name: "MAPPA", kind: "STUDIO" }],
    seasons: [
      { number: 1, episodes: 24, year: 2020 },
      { number: 2, episodes: 23, year: 2023 },
    ],
  },
  {
    externalId: "anime-demon-slayer",
    type: "ANIME",
    title: "Demon Slayer",
    originalTitle: "Kimetsu no Yaiba",
    synopsis:
      "A boy sells charcoal, comes home to a massacre, and spends the next several years carrying his demon sister in a box while learning to breathe correctly.",
    firstAirYear: 2019,
    airingStatus: "AIRING",
    runtime: 24,
    language: "ja",
    popularity: 97.3,
    externalRating: 8.5,
    genres: ["Action", "Fantasy", "Supernatural"],
    credits: [{ name: "ufotable", kind: "STUDIO" }],
    seasons: [
      { number: 1, episodes: 26, year: 2019 },
      { number: 2, episodes: 18, year: 2021 },
      { number: 3, episodes: 11, year: 2023 },
      { number: 4, episodes: 8, year: 2024 },
    ],
  },
  {
    externalId: "anime-vinland-saga",
    type: "ANIME",
    title: "Vinland Saga",
    synopsis:
      "A Viking revenge story that gradually, deliberately becomes an argument against Viking revenge stories.",
    firstAirYear: 2019,
    airingStatus: "AIRING",
    runtime: 24,
    language: "ja",
    popularity: 88.9,
    externalRating: 8.8,
    genres: ["Action", "Drama", "Historical", "Psychological"],
    credits: [{ name: "Wit Studio", kind: "STUDIO" }, { name: "MAPPA", kind: "STUDIO" }],
    seasons: [
      { number: 1, episodes: 24, year: 2019 },
      { number: 2, episodes: 24, year: 2023 },
    ],
  },
  {
    externalId: "anime-chainsaw-man",
    type: "ANIME",
    title: "Chainsaw Man",
    synopsis:
      "A boy in crippling debt fuses with his chainsaw dog and joins a government agency that treats him roughly as well as everyone else has.",
    firstAirYear: 2022,
    airingStatus: "AIRING",
    runtime: 24,
    language: "ja",
    popularity: 93.5,
    externalRating: 8.5,
    genres: ["Action", "Horror", "Supernatural", "Comedy"],
    credits: [{ name: "MAPPA", kind: "STUDIO" }],
    seasons: [{ number: 1, episodes: 12, year: 2022 }],
  },
  {
    externalId: "anime-fmab",
    type: "ANIME",
    title: "Fullmetal Alchemist: Brotherhood",
    synopsis:
      "Two brothers break the one rule of alchemy trying to resurrect their mother, and spend the rest of their lives paying an invoice that keeps getting larger.",
    firstAirYear: 2009,
    lastAirYear: 2010,
    airingStatus: "ENDED",
    runtime: 24,
    language: "ja",
    popularity: 92.8,
    externalRating: 9.1,
    genres: ["Action", "Adventure", "Drama", "Fantasy"],
    credits: [{ name: "Bones", kind: "STUDIO" }],
    seasons: [{ number: 1, episodes: 64, year: 2009 }],
  },
  {
    externalId: "anime-steins-gate",
    type: "ANIME",
    title: "Steins;Gate",
    synopsis:
      "A self-styled mad scientist microwaves a banana and accidentally invents time travel. The first twelve episodes are a comedy. The rest are not.",
    firstAirYear: 2011,
    airingStatus: "ENDED",
    runtime: 24,
    language: "ja",
    popularity: 85.4,
    externalRating: 9.0,
    genres: ["Sci-Fi", "Thriller", "Psychological", "Drama"],
    credits: [{ name: "White Fox", kind: "STUDIO" }],
    seasons: [{ number: 1, episodes: 24, year: 2011 }],
  },
  {
    externalId: "anime-code-geass",
    type: "ANIME",
    title: "Code Geass",
    synopsis:
      "An exiled prince gains the power to make anyone obey a single command, and uses it to start a revolution he cannot stop.",
    firstAirYear: 2006,
    lastAirYear: 2008,
    airingStatus: "ENDED",
    runtime: 24,
    language: "ja",
    popularity: 84.1,
    externalRating: 8.7,
    genres: ["Action", "Drama", "Sci-Fi", "Psychological"],
    credits: [{ name: "Sunrise", kind: "STUDIO" }],
    seasons: [
      { number: 1, episodes: 25, year: 2006 },
      { number: 2, episodes: 25, year: 2008 },
    ],
  },
  {
    externalId: "anime-monster",
    type: "ANIME",
    title: "Monster",
    synopsis:
      "A brilliant surgeon saves a boy's life and spends the next decade discovering exactly how much of a mistake that was.",
    firstAirYear: 2004,
    lastAirYear: 2005,
    airingStatus: "ENDED",
    runtime: 24,
    language: "ja",
    popularity: 79.6,
    externalRating: 8.8,
    genres: ["Mystery", "Psychological", "Thriller", "Drama"],
    credits: [{ name: "Madhouse", kind: "STUDIO" }],
    seasons: [{ number: 1, episodes: 74, year: 2004 }],
  },
  {
    externalId: "anime-cowboy-bebop",
    type: "ANIME",
    title: "Cowboy Bebop",
    synopsis:
      "Bounty hunters in a rusting spaceship fail to make rent, repeatedly, beautifully, to jazz.",
    firstAirYear: 1998,
    airingStatus: "ENDED",
    runtime: 24,
    language: "ja",
    popularity: 81.2,
    externalRating: 8.9,
    genres: ["Action", "Sci-Fi", "Drama"],
    credits: [{ name: "Sunrise", kind: "STUDIO" }],
    seasons: [{ number: 1, episodes: 26, year: 1998 }],
  },
  {
    externalId: "anime-hunter-x-hunter",
    type: "ANIME",
    title: "Hunter x Hunter",
    synopsis:
      "A cheerful boy sets out to find his absent father and keeps wandering into arcs that are far darker than he is.",
    firstAirYear: 2011,
    lastAirYear: 2014,
    airingStatus: "ENDED",
    runtime: 23,
    language: "ja",
    popularity: 90.3,
    externalRating: 9.0,
    genres: ["Action", "Adventure", "Fantasy"],
    credits: [{ name: "Madhouse", kind: "STUDIO" }],
    seasons: [
      { number: 1, episodes: 26, year: 2011 },
      { number: 2, episodes: 32, year: 2012 },
      { number: 3, episodes: 20, year: 2012 },
      { number: 4, episodes: 24, year: 2013 },
      { number: 5, episodes: 22, year: 2013 },
      { number: 6, episodes: 24, year: 2014 },
    ],
  },
  {
    externalId: "anime-mob-psycho",
    type: "ANIME",
    title: "Mob Psycho 100",
    synopsis:
      "The most powerful esper alive would rather be good at talking to people, and the show agrees with him.",
    firstAirYear: 2016,
    lastAirYear: 2022,
    airingStatus: "ENDED",
    runtime: 24,
    language: "ja",
    popularity: 82.7,
    externalRating: 8.6,
    genres: ["Action", "Comedy", "Supernatural", "Slice of Life"],
    credits: [{ name: "Bones", kind: "STUDIO" }],
    seasons: [
      { number: 1, episodes: 12, year: 2016 },
      { number: 2, episodes: 13, year: 2019 },
      { number: 3, episodes: 12, year: 2022 },
    ],
  },
  {
    externalId: "anime-spy-x-family",
    type: "ANIME",
    title: "Spy x Family",
    synopsis:
      "A spy, an assassin and a telepath form a fake family. Only the child knows, and she is having the time of her life.",
    firstAirYear: 2022,
    airingStatus: "AIRING",
    runtime: 24,
    language: "ja",
    popularity: 89.4,
    externalRating: 8.5,
    genres: ["Action", "Comedy", "Slice of Life"],
    credits: [{ name: "Wit Studio", kind: "STUDIO" }, { name: "CloverWorks", kind: "STUDIO" }],
    seasons: [
      { number: 1, episodes: 25, year: 2022 },
      { number: 2, episodes: 12, year: 2023 },
    ],
  },
  {
    externalId: "anime-made-in-abyss",
    type: "ANIME",
    title: "Made in Abyss",
    synopsis:
      "Adorable children descend into a beautiful hole. Do not let the art style fool you about what is down there.",
    firstAirYear: 2017,
    airingStatus: "AIRING",
    runtime: 25,
    language: "ja",
    popularity: 76.8,
    externalRating: 8.7,
    genres: ["Adventure", "Fantasy", "Drama", "Horror"],
    credits: [{ name: "Kinema Citrus", kind: "STUDIO" }],
    seasons: [
      { number: 1, episodes: 13, year: 2017 },
      { number: 2, episodes: 12, year: 2022 },
    ],
  },
  {
    externalId: "anime-86",
    type: "ANIME",
    title: "86 EIGHTY-SIX",
    synopsis:
      "A country claims its war has no casualties. It has plenty; it has simply decided those people are not citizens.",
    firstAirYear: 2021,
    airingStatus: "ENDED",
    runtime: 24,
    language: "ja",
    popularity: 74.2,
    externalRating: 8.6,
    genres: ["Action", "Drama", "Sci-Fi", "Psychological"],
    credits: [{ name: "A-1 Pictures", kind: "STUDIO" }],
    seasons: [
      { number: 1, episodes: 11, year: 2021 },
      { number: 2, episodes: 12, year: 2021 },
    ],
  },
  {
    externalId: "anime-parasyte",
    type: "ANIME",
    title: "Parasyte: The Maxim",
    synopsis:
      "An alien takes over a teenager's right hand instead of his brain, and the two of them have to negotiate being a person.",
    firstAirYear: 2014,
    lastAirYear: 2015,
    airingStatus: "ENDED",
    runtime: 24,
    language: "ja",
    popularity: 78.3,
    externalRating: 8.3,
    genres: ["Horror", "Sci-Fi", "Psychological", "Action"],
    credits: [{ name: "Madhouse", kind: "STUDIO" }],
    seasons: [{ number: 1, episodes: 24, year: 2014 }],
  },
  {
    externalId: "anime-erased",
    type: "ANIME",
    title: "Erased",
    synopsis:
      "A man who involuntarily rewinds time by a few minutes is thrown back eighteen years to prevent three murders.",
    firstAirYear: 2016,
    airingStatus: "ENDED",
    runtime: 23,
    language: "ja",
    popularity: 73.9,
    externalRating: 8.3,
    genres: ["Mystery", "Psychological", "Thriller", "Drama"],
    credits: [{ name: "A-1 Pictures", kind: "STUDIO" }],
    seasons: [{ number: 1, episodes: 12, year: 2016 }],
  },
  {
    externalId: "anime-evangelion",
    type: "ANIME",
    title: "Neon Genesis Evangelion",
    synopsis:
      "A boy is told to get in the robot. The show spends twenty-six episodes explaining why he cannot.",
    firstAirYear: 1995,
    lastAirYear: 1996,
    airingStatus: "ENDED",
    runtime: 24,
    language: "ja",
    popularity: 80.5,
    externalRating: 8.5,
    genres: ["Sci-Fi", "Psychological", "Drama", "Action"],
    credits: [{ name: "Gainax", kind: "STUDIO" }],
    seasons: [{ number: 1, episodes: 26, year: 1995 }],
  },
  {
    externalId: "anime-frieren",
    type: "ANIME",
    title: "Frieren: Beyond Journey's End",
    synopsis:
      "The elf who helped kill the demon king outlives the party by centuries and finally starts wondering who they were.",
    firstAirYear: 2023,
    airingStatus: "AIRING",
    runtime: 24,
    language: "ja",
    popularity: 95.1,
    externalRating: 9.0,
    genres: ["Adventure", "Drama", "Fantasy", "Slice of Life"],
    credits: [{ name: "Madhouse", kind: "STUDIO" }],
    seasons: [{ number: 1, episodes: 28, year: 2023 }],
  },
  {
    externalId: "anime-cyberpunk-edgerunners",
    type: "ANIME",
    title: "Cyberpunk: Edgerunners",
    synopsis:
      "A kid from the wrong district chases the only exit Night City sells, and it works exactly as advertised.",
    firstAirYear: 2022,
    airingStatus: "ENDED",
    runtime: 25,
    language: "ja",
    popularity: 86.2,
    externalRating: 8.6,
    genres: ["Action", "Sci-Fi", "Drama"],
    credits: [{ name: "Studio Trigger", kind: "STUDIO" }],
    seasons: [{ number: 1, episodes: 10, year: 2022 }],
  },
  {
    externalId: "anime-pluto",
    type: "ANIME",
    title: "Pluto",
    synopsis:
      "A robot detective investigates the murders of the world's seven most advanced robots, one of whom is him.",
    firstAirYear: 2023,
    airingStatus: "ENDED",
    runtime: 60,
    language: "ja",
    popularity: 71.4,
    externalRating: 8.7,
    genres: ["Mystery", "Sci-Fi", "Drama", "Psychological"],
    credits: [{ name: "Studio M2", kind: "STUDIO" }],
    seasons: [{ number: 1, episodes: 8, year: 2023 }],
  },
];

/** Live-action TV. */
export const SEED_TV: SeedShow[] = [
  {
    externalId: "tv-breaking-bad",
    type: "TV",
    title: "Breaking Bad",
    synopsis:
      "A high school chemistry teacher with terminal cancer starts cooking meth to provide for his family, and discovers he is extremely good at it and was never doing it for them.",
    firstAirYear: 2008,
    lastAirYear: 2013,
    airingStatus: "ENDED",
    runtime: 47,
    language: "en",
    popularity: 97.9,
    externalRating: 8.9,
    genres: ["Crime", "Drama", "Thriller"],
    credits: [{ name: "AMC", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 7, titles: BREAKING_BAD_S1, year: 2008 },
      { number: 2, episodes: 13, year: 2009 },
      { number: 3, episodes: 13, year: 2010 },
      { number: 4, episodes: 13, year: 2011 },
      { number: 5, episodes: 16, year: 2012 },
    ],
  },
  {
    externalId: "tv-better-call-saul",
    type: "TV",
    title: "Better Call Saul",
    synopsis:
      "The slow, immaculate demolition of a man who kept choosing the worse option because the better one required being someone else.",
    firstAirYear: 2015,
    lastAirYear: 2022,
    airingStatus: "ENDED",
    runtime: 46,
    language: "en",
    popularity: 88.6,
    externalRating: 8.8,
    genres: ["Crime", "Drama"],
    credits: [{ name: "AMC", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 10, year: 2015 },
      { number: 2, episodes: 10, year: 2016 },
      { number: 3, episodes: 10, year: 2017 },
      { number: 4, episodes: 10, year: 2018 },
      { number: 5, episodes: 10, year: 2020 },
      { number: 6, episodes: 13, year: 2022 },
    ],
  },
  {
    externalId: "tv-the-boys",
    type: "TV",
    title: "The Boys",
    synopsis:
      "Superheroes are a publicly traded brand, and the brand is not doing well behind the scenes.",
    firstAirYear: 2019,
    airingStatus: "AIRING",
    runtime: 60,
    language: "en",
    popularity: 94.7,
    externalRating: 8.5,
    genres: ["Action", "Comedy", "Sci-Fi", "Drama"],
    credits: [{ name: "Prime Video", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 8, year: 2019 },
      { number: 2, episodes: 8, year: 2020 },
      { number: 3, episodes: 8, year: 2022 },
      { number: 4, episodes: 8, year: 2024 },
    ],
  },
  {
    externalId: "tv-dark",
    type: "TV",
    title: "Dark",
    synopsis:
      "A German town where a missing child is a scheduling problem across four time periods and everyone is their own grandfather.",
    firstAirYear: 2017,
    lastAirYear: 2020,
    airingStatus: "ENDED",
    runtime: 55,
    language: "de",
    popularity: 87.3,
    externalRating: 8.7,
    genres: ["Mystery", "Sci-Fi", "Thriller", "Drama"],
    credits: [{ name: "Netflix", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 10, year: 2017 },
      { number: 2, episodes: 8, year: 2019 },
      { number: 3, episodes: 8, year: 2020 },
    ],
  },
  {
    externalId: "tv-stranger-things",
    type: "TV",
    title: "Stranger Things",
    synopsis:
      "Kids in 1980s Indiana ride bikes toward a government conspiracy and a dimension that wants them very much.",
    firstAirYear: 2016,
    airingStatus: "AIRING",
    runtime: 51,
    language: "en",
    popularity: 96.1,
    externalRating: 8.6,
    genres: ["Sci-Fi", "Horror", "Drama", "Mystery"],
    credits: [{ name: "Netflix", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 8, year: 2016 },
      { number: 2, episodes: 9, year: 2017 },
      { number: 3, episodes: 8, year: 2019 },
      { number: 4, episodes: 9, year: 2022 },
    ],
  },
  {
    externalId: "tv-the-walking-dead",
    type: "TV",
    title: "The Walking Dead",
    synopsis:
      "A sheriff wakes from a coma into the apocalypse and then keeps going for eleven seasons.",
    firstAirYear: 2010,
    lastAirYear: 2022,
    airingStatus: "ENDED",
    runtime: 44,
    language: "en",
    popularity: 83.2,
    externalRating: 8.1,
    genres: ["Horror", "Drama", "Thriller"],
    credits: [{ name: "AMC", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 6, year: 2010 },
      { number: 2, episodes: 13, year: 2011 },
      { number: 3, episodes: 16, year: 2012 },
      { number: 4, episodes: 16, year: 2013 },
      { number: 5, episodes: 16, year: 2014 },
      { number: 6, episodes: 16, year: 2015 },
      { number: 7, episodes: 16, year: 2016 },
      { number: 8, episodes: 16, year: 2017 },
      { number: 9, episodes: 16, year: 2018 },
      { number: 10, episodes: 22, year: 2019 },
      { number: 11, episodes: 24, year: 2021 },
    ],
  },
  {
    externalId: "tv-game-of-thrones",
    type: "TV",
    title: "Game of Thrones",
    synopsis:
      "Noble houses fight over a chair for eight seasons. Opinions on the last two remain a personality test.",
    firstAirYear: 2011,
    lastAirYear: 2019,
    airingStatus: "ENDED",
    runtime: 57,
    language: "en",
    popularity: 92.4,
    externalRating: 8.4,
    genres: ["Fantasy", "Drama", "Action"],
    credits: [{ name: "HBO", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 10, year: 2011 },
      { number: 2, episodes: 10, year: 2012 },
      { number: 3, episodes: 10, year: 2013 },
      { number: 4, episodes: 10, year: 2014 },
      { number: 5, episodes: 10, year: 2015 },
      { number: 6, episodes: 10, year: 2016 },
      { number: 7, episodes: 7, year: 2017 },
      { number: 8, episodes: 6, year: 2019 },
    ],
  },
  {
    externalId: "tv-chernobyl",
    type: "TV",
    title: "Chernobyl",
    synopsis:
      "Five hours on the cost of lies, told mostly through people quietly doing arithmetic they wish were wrong.",
    firstAirYear: 2019,
    airingStatus: "ENDED",
    runtime: 65,
    language: "en",
    popularity: 79.8,
    externalRating: 9.3,
    genres: ["Drama", "Historical", "Thriller"],
    credits: [{ name: "HBO", kind: "NETWORK" }],
    seasons: [{ number: 1, episodes: 5, titles: CHERNOBYL, year: 2019 }],
  },
  {
    externalId: "tv-severance",
    type: "TV",
    title: "Severance",
    synopsis:
      "Employees surgically split their memories between work and home, and one half starts wondering what the other half agreed to.",
    firstAirYear: 2022,
    airingStatus: "AIRING",
    runtime: 50,
    language: "en",
    popularity: 91.6,
    externalRating: 8.7,
    genres: ["Sci-Fi", "Thriller", "Drama", "Psychological"],
    credits: [{ name: "Apple TV+", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 9, year: 2022 },
      { number: 2, episodes: 10, year: 2025 },
    ],
  },
  {
    externalId: "tv-the-bear",
    type: "TV",
    title: "The Bear",
    synopsis:
      "A fine-dining chef inherits his brother's sandwich shop and everyone yells for three seasons.",
    firstAirYear: 2022,
    airingStatus: "AIRING",
    runtime: 32,
    language: "en",
    popularity: 85.9,
    externalRating: 8.4,
    genres: ["Drama", "Comedy"],
    credits: [{ name: "FX", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 8, year: 2022 },
      { number: 2, episodes: 10, year: 2023 },
      { number: 3, episodes: 10, year: 2024 },
    ],
  },
  {
    externalId: "tv-succession",
    type: "TV",
    title: "Succession",
    synopsis:
      "Four adult children compete for the approval of a father who has never once had any to give.",
    firstAirYear: 2018,
    lastAirYear: 2023,
    airingStatus: "ENDED",
    runtime: 60,
    language: "en",
    popularity: 84.3,
    externalRating: 8.8,
    genres: ["Drama", "Comedy"],
    credits: [{ name: "HBO", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 10, year: 2018 },
      { number: 2, episodes: 10, year: 2019 },
      { number: 3, episodes: 9, year: 2021 },
      { number: 4, episodes: 10, year: 2023 },
    ],
  },
  {
    externalId: "tv-mr-robot",
    type: "TV",
    title: "Mr. Robot",
    synopsis:
      "A cybersecurity engineer with severe dissociation joins a hacking collective, or possibly founded it.",
    firstAirYear: 2015,
    lastAirYear: 2019,
    airingStatus: "ENDED",
    runtime: 49,
    language: "en",
    popularity: 77.4,
    externalRating: 8.5,
    genres: ["Drama", "Thriller", "Crime", "Psychological"],
    credits: [{ name: "USA Network", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 10, year: 2015 },
      { number: 2, episodes: 12, year: 2016 },
      { number: 3, episodes: 10, year: 2017 },
      { number: 4, episodes: 13, year: 2019 },
    ],
  },
  {
    externalId: "tv-fleabag",
    type: "TV",
    title: "Fleabag",
    synopsis:
      "A woman tells you everything directly to camera except the one thing the show is actually about.",
    firstAirYear: 2016,
    lastAirYear: 2019,
    airingStatus: "ENDED",
    runtime: 27,
    language: "en",
    popularity: 72.1,
    externalRating: 8.7,
    genres: ["Comedy", "Drama"],
    credits: [{ name: "BBC", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 6, year: 2016 },
      { number: 2, episodes: 6, year: 2019 },
    ],
  },
  {
    externalId: "tv-true-detective",
    type: "TV",
    title: "True Detective",
    synopsis:
      "An anthology about detectives whose cases are less interesting than their monologues, at least in the good season.",
    firstAirYear: 2014,
    airingStatus: "AIRING",
    runtime: 55,
    language: "en",
    popularity: 76.2,
    externalRating: 8.3,
    genres: ["Crime", "Drama", "Mystery", "Thriller"],
    credits: [{ name: "HBO", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 8, year: 2014 },
      { number: 2, episodes: 8, year: 2015 },
      { number: 3, episodes: 8, year: 2019 },
      { number: 4, episodes: 6, year: 2024 },
    ],
  },
  {
    externalId: "tv-peaky-blinders",
    type: "TV",
    title: "Peaky Blinders",
    synopsis:
      "A Birmingham crime family moves upward through British society without ever getting less violent about it.",
    firstAirYear: 2013,
    lastAirYear: 2022,
    airingStatus: "ENDED",
    runtime: 58,
    language: "en",
    popularity: 86.7,
    externalRating: 8.5,
    genres: ["Crime", "Drama", "Historical"],
    credits: [{ name: "BBC", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 6, year: 2013 },
      { number: 2, episodes: 6, year: 2014 },
      { number: 3, episodes: 6, year: 2016 },
      { number: 4, episodes: 6, year: 2017 },
      { number: 5, episodes: 6, year: 2019 },
      { number: 6, episodes: 6, year: 2022 },
    ],
  },
  {
    externalId: "tv-the-last-of-us",
    type: "TV",
    title: "The Last of Us",
    synopsis:
      "A smuggler escorts an immune teenager across a fungal apocalypse and makes a decision at the end that everyone is still arguing about.",
    firstAirYear: 2023,
    airingStatus: "AIRING",
    runtime: 55,
    language: "en",
    popularity: 90.8,
    externalRating: 8.7,
    genres: ["Drama", "Horror", "Sci-Fi"],
    credits: [{ name: "HBO", kind: "NETWORK" }],
    seasons: [{ number: 1, episodes: 9, year: 2023 }],
  },
  {
    externalId: "tv-arcane",
    type: "TV",
    title: "Arcane",
    synopsis:
      "Two sisters end up on opposite sides of a city that was always going to make them choose.",
    firstAirYear: 2021,
    lastAirYear: 2024,
    airingStatus: "ENDED",
    runtime: 42,
    language: "en",
    popularity: 89.9,
    externalRating: 9.0,
    genres: ["Action", "Fantasy", "Drama", "Sci-Fi"],
    credits: [{ name: "Netflix", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 9, year: 2021 },
      { number: 2, episodes: 9, year: 2024 },
    ],
  },
  {
    externalId: "tv-black-mirror",
    type: "TV",
    title: "Black Mirror",
    synopsis:
      "An anthology that was speculative fiction when it started and is increasingly just the news.",
    firstAirYear: 2011,
    airingStatus: "AIRING",
    runtime: 60,
    language: "en",
    popularity: 82.5,
    externalRating: 8.3,
    genres: ["Sci-Fi", "Thriller", "Drama", "Psychological"],
    credits: [{ name: "Netflix", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 3, year: 2011 },
      { number: 2, episodes: 4, year: 2013 },
      { number: 3, episodes: 6, year: 2016 },
      { number: 4, episodes: 6, year: 2017 },
      { number: 5, episodes: 3, year: 2019 },
      { number: 6, episodes: 5, year: 2023 },
    ],
  },
  {
    externalId: "tv-andor",
    type: "TV",
    title: "Andor",
    synopsis:
      "A prequel that is really about how ordinary bureaucratic cruelty manufactures revolutionaries.",
    firstAirYear: 2022,
    airingStatus: "AIRING",
    runtime: 45,
    language: "en",
    popularity: 81.3,
    externalRating: 8.6,
    genres: ["Sci-Fi", "Drama", "Action"],
    credits: [{ name: "Disney+", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 12, year: 2022 },
      { number: 2, episodes: 12, year: 2025 },
    ],
  },
  {
    externalId: "tv-house",
    type: "TV",
    title: "House M.D.",
    synopsis:
      "It is never lupus. A misanthrope solves medical mysteries while everyone around him absorbs the damage.",
    firstAirYear: 2004,
    lastAirYear: 2012,
    airingStatus: "ENDED",
    runtime: 44,
    language: "en",
    popularity: 80.1,
    externalRating: 8.4,
    genres: ["Drama", "Mystery"],
    credits: [{ name: "FOX", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 22, year: 2004 },
      { number: 2, episodes: 24, year: 2005 },
      { number: 3, episodes: 24, year: 2006 },
      { number: 4, episodes: 16, year: 2007 },
      { number: 5, episodes: 24, year: 2008 },
      { number: 6, episodes: 21, year: 2009 },
      { number: 7, episodes: 23, year: 2010 },
      { number: 8, episodes: 22, year: 2011 },
    ],
  },
  {
    externalId: "tv-the-office",
    type: "TV",
    title: "The Office",
    synopsis:
      "A documentary crew films a paper company for nine years and nobody ever asks why they are still there.",
    firstAirYear: 2005,
    lastAirYear: 2013,
    airingStatus: "ENDED",
    runtime: 22,
    language: "en",
    popularity: 88.2,
    externalRating: 8.6,
    genres: ["Comedy"],
    credits: [{ name: "NBC", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 6, year: 2005 },
      { number: 2, episodes: 22, year: 2005 },
      { number: 3, episodes: 25, year: 2006 },
      { number: 4, episodes: 19, year: 2007 },
      { number: 5, episodes: 28, year: 2008 },
      { number: 6, episodes: 26, year: 2009 },
      { number: 7, episodes: 26, year: 2010 },
      { number: 8, episodes: 24, year: 2011 },
      { number: 9, episodes: 25, year: 2012 },
    ],
  },
  {
    externalId: "tv-sherlock",
    type: "TV",
    title: "Sherlock",
    synopsis:
      "Ninety-minute episodes, three at a time, several years apart. The wait was part of the experience.",
    firstAirYear: 2010,
    lastAirYear: 2017,
    airingStatus: "ENDED",
    runtime: 88,
    language: "en",
    popularity: 78.9,
    externalRating: 8.5,
    genres: ["Crime", "Drama", "Mystery"],
    credits: [{ name: "BBC", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 3, year: 2010 },
      { number: 2, episodes: 3, year: 2012 },
      { number: 3, episodes: 3, year: 2014 },
      { number: 4, episodes: 3, year: 2017 },
    ],
  },
  {
    externalId: "tv-westworld",
    type: "TV",
    title: "Westworld",
    synopsis:
      "A theme park full of androids gains self-awareness, and so, gradually, does the audience about season three.",
    firstAirYear: 2016,
    lastAirYear: 2022,
    airingStatus: "CANCELLED",
    runtime: 62,
    language: "en",
    popularity: 74.6,
    externalRating: 8.0,
    genres: ["Sci-Fi", "Drama", "Mystery", "Thriller"],
    credits: [{ name: "HBO", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 10, year: 2016 },
      { number: 2, episodes: 10, year: 2018 },
      { number: 3, episodes: 8, year: 2020 },
      { number: 4, episodes: 8, year: 2022 },
    ],
  },
  {
    externalId: "tv-squid-game",
    type: "TV",
    title: "Squid Game",
    synopsis:
      "Desperate people play children's games for money. The games are not the horrifying part.",
    firstAirYear: 2021,
    airingStatus: "AIRING",
    runtime: 55,
    language: "ko",
    popularity: 93.1,
    externalRating: 8.0,
    genres: ["Thriller", "Drama", "Action", "Mystery"],
    credits: [{ name: "Netflix", kind: "NETWORK" }],
    seasons: [
      { number: 1, episodes: 9, year: 2021 },
      { number: 2, episodes: 7, year: 2024 },
    ],
  },
];

export const SEED_CATALOGUE: SeedShow[] = [...SEED_ANIME, ...SEED_TV];
